version: '2'
services:
  lb:
    build: .
    ports: 
    - 8080:80
    - 8443:443
    - 1936:1936
    environment:
      MODE: http
      SERVICE_NAME: web
      SERVICE_PORT: 80
      BALANCE_ALGORITHM: source
      COOKIE: JSESSIONID prefix
      SSL_CERT: -----BEGIN CERTIFICATE-----\nMIIB+zCCAWQCCQDc/tVzGKP4ojANBgkqhkiG9w0BAQUFADBCMQswCQYDVQQGEwJY\nWDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZhdWx0IENvbXBh\nbnkgTHRkMB4XDTE3MDExNTEzMTMyNloXDTE4MDExNTEzMTMyNlowQjELMAkGA1UE\nBhMCWFgxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTEcMBoGA1UECgwTRGVmYXVsdCBD\nb21wYW55IEx0ZDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA56SvY01154k0\n5YlxOkvemYxjLGHnu/+0lwqZpcEjakdGSoH3fSXwie5Nu7nW3JGaGfHMLeoq58Xt\nfkS6Lm+7LonSp8BnaW7IahqRrUXR7cYp1iiPc4ctTsvLXYT+h68e7+FVa7Glg5th\nSk2QwRXJBUWvf89W2uDTsbxrMFbtlIsCAwEAATANBgkqhkiG9w0BAQUFAAOBgQAd\nqLqpVigzRrREUPlfFO0vUoH3hMEI3d5wffYaY7XHpziYNMs9yr56xEQmzfgAi8X2\nwpKPqBsOhSH2Szg8EjmZQKsSuyqPZbAmXP5IsxTNIu2LWlFDvPPg/APlML/S2ZSV\n10SfBBbjKir5zl9j3pEzq4PgCuDnMF0yBt3CjtmkEg==\n-----END CERTIFICATE-----\n-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDnpK9jTXXniTTliXE6S96ZjGMsYee7/7SXCpmlwSNqR0ZKgfd9\nJfCJ7k27udbckZoZ8cwt6irnxe1+RLoub7suidKnwGdpbshqGpGtRdHtxinWKI9z\nhy1Oy8tdhP6Hrx7v4VVrsaWDm2FKTZDBFckFRa9/z1ba4NOxvGswVu2UiwIDAQAB\nAoGBALuPfDfSu5obXcpRzG2giwAXTSHdsG5n8IiwG5K73Por9f1UWNlrg+WbIDPV\nmOUFvBovz9yJk+4RNGieK4Z4D71nIxYGBy2Tkjlxzh//OjUCUjbAkZDvdGWqFOuA\nQJSpaxRba0tyAN5Jf4ymHgLBfzztj0MEJcotIJAyPyI0InThAkEA/9fmkaDaIkW5\n/WZAlZBSL4xBwJWHpVagvXvAPAuvxmd7VCsGVSQKHqBnyeURjT9GsT7lRttXRESv\n2qIclpO1sQJBAOfI/dGFfyh26W0YbXL0CYL8CKXmKeD5M6qoc1eG9Cttiy873/u3\nAhM+GljlPWcxVm361yN0GP7b96fKkgytcPsCQQDQjH+IiiQF9+yKYMWYpVI5LA2V\nHM67ugfBLZUf3S7lfgkMLR42XPBa0sqHytAp4UCQzwI6ZiWWop7ui2LeY32hAkB9\nI6fd0hxoBWNbkj+tO5JTFK26m/xqSUEa112GmQcE11y5ALOaHCFTsEjbS9EOALYw\nJKi4rHq+RpZ8EcMucwm3AkATvtx517FU1yu/pFtQ0y03v3JAqMF0x86Vf3QXugnm\n16R+MKUo5k9VGv84LpfYYl+xehdkqwqZa8NOFeJaJDwD\n-----END RSA PRIVATE KEY-----
  web:
    image: daocloud.io/daocloud/dao-2048

