version: '2'
services:
  lb:
    build: .
    ports: 
    - 8080:80
    - 8443:443
    - 1936
    environment:
      MODE: http
      SERVICE_NAME: web
      SERVICE_PORT: 80
      BALANCE_ALGORITHM: source
      APPSESSION: JSESSIONID len 64 timeout 3h prefix
      COOKIE: JSESSIONID prefix
  web:
    image: daocloud.io/daocloud/dao-2048

